### ISSUE TITLE
Unit in CH4 extension

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/CEDS#11]
The CH4 extension file in  https://www.geosci-model-dev.net/11/369/2018/gmd-11-369-2018-assets.html doesn't have a unit column. It's the same as the CH4 file but might be worth including if you do an update anyways (#9).

Related question, are the decadal estimates to be understood as estimates of emissions in the respective years?

**Comment by ssmithClimate** [comment]
Thanks, good suggestion.  Yes, the estimates are, formally, estimates of emissions in each of those years.
