### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/CEDS#13]
The supplement of the paper states in the PDF

```
© Author(s) 2018. This work is distributed under
the Creative Commons Attribution 3.0 License.
```
and below

```
The copyright of individual parts of the supplement might differ from the CC BY 3.0 License.
```

The input datasets at https://doi.org/10.22033/ESGF/input4MIPs.1241 are under

```
Creative Commons Attribution 4.0 International License (CC BY-SA 4.0)
```

What is license for the CSV files in the supplement? They are derived from the gridded CMIP data, arent'y they?

**Comment by ssmithClimate** [comment]
Actually the other way around, the gridded data are generated from data by country. So the .csv files distributed with the journal paper are open source using the default journal paper's license.
