### ISSUE TITLE
CSV files for scenarios

### ISSUE THREAD

**Issue by rich-HJ** [JGCRI/CEDS#14]
The historical CO2 emission cdf files had an associated csv file to sanity check to global values. I cannot find similar files for the scenario files. Have I missed them or were they not made for the future emission files?

**Comment by calebbraun** [comment]
The CO2 global checksum files will be added to the others [here](http://www.globalchange.umd.edu/ceds/ceds-cmip6-data/) soon. The file below contains the future emission global totals for CO2 in the meantime.

[CO2-checksums.zip](https://github.com/JGCRI/CEDS/files/2985439/CO2-checksums.zip)

**Comment by ssmithClimate** [comment]
Closing issue, as the CO2 checksum files have now been added to the CEDS web page.
