### ISSUE TITLE
US and Canada Agricultural NOx Emissions Too Low

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/CEDS#17]
It appears that NOx emissions from agriculture (fertilizer and animal manure) were not included in the USA and Canada emission inventories used to produced the CEDS emissions data. As a result, agricultural NOx emissions in the CEDS data to date are too low. (Thanks to Maria Val Martin for pointing this out.)

**Comment by emcduffie** [comment]
Hi Steve,

I’m working on a longer email to you but I wanted to quickly check, does the issue below mean that default CEDS NOx manure management and soil emissions (fertilizer application) should not be included in the agriculture scaling sector when scaling CEDS NOx to US and Canada regional inventories?

Thanks,
Erin

-----
Erin E. McDuffie
Post Doctoral Fellow
Department of Physics and Atmospheric Science
Dalhousie University
Halifax, NS B2H 4R2
www.erinemcduffie.com<http://www.erinemcduffie.com>

On Oct 23, 2019, at 12:48 PM, Steve Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


It appears that NOx emissions from agriculture (fertilizer and animal manure) were not included in the USA and Canada emission inventories used to produced the CEDS emissions data. As a result, agricultural NOx emissions in the CEDS data to date are too low. (Thanks to Maria Val Martin for pointing this out.)

**Comment by ssmithClimate** [comment]
Yes. Since it appears that these are not included in the country inventory, they shouldn't be included in the scaling mapping. This means there needs to be a different scaling mapping file for NOx than for other species.

**Comment by emcduffie** [comment]
Got it, will do. Thanks again.

Erin



On Oct 24, 2019, at 6:07 PM, Steve Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. Since it appears that these are not included in the country inventory, they shouldn't be included in the scaling mapping. This means there needs to be a different scaling mapping file for NOx than for other species.

**Comment by ssmithClimate** [comment]
Fixed as of v_2020_9_11
