### ISSUE TITLE
IND and AGR Emissions over Australia too low?

### ISSUE THREAD

**Issue by emcduffie** [JGCRI/CEDS#18]
The Australia_scaling_mapping.xlsx file currently groups Australia NPI emissions for 'Coal Mining' with CEDS fugitive emissions (1B1, 1B2, 1B2d), 'Metal Ore Mining' with CEDS metal production (2C, 1A2b, 1A2a) and 'Other Non-Metallic Mineral Mining and Quarrying' with CEDS non-metallic minerals (2A1, 2A2, 2A6, 1A2f, and 1A2g (Ind-Comb-mining-quarrying)). Based on the magnitude of the Australia NPI mining emissions (Coal + metal + non-metal), it appears that these NPI mining sectors should instead be mapped to the CEDS industry scaling sector, along with CEDS sector 1A2g (ind-comb-mining). Due to the magnitude of NPI coal mining emissions, the current mapping is resulting in a CEDS scaling factor of 100 for fugitive emissions in recent years. I believe that this is resulting in aggregate CEDS ENE emissions that are slightly too large and CEDS IND emissions that are too low (since mining emissions are currently included in the aggregate ENE sector, but not the IND sector). 

In addition, the Australia NPI agricultural emissions do not appear to include soil emissions from fertilizer application. CEDS soil emissions are currently scaled to all other reported NPI AGR emissions (livestock and grain farming), which will cause the final CEDS soil emissions over Australia to be too low.

**Comment by ssmithClimate** [comment]
Resolved as of [Feb 05 2021](https://github.com/JGCRI/CEDS/pull/32) release.
