### ISSUE TITLE
Question: IEA energy statistics database

### ISSUE THREAD

**Issue by ctessum** [JGCRI/CEDS#21]
Hello,

The wiki says that the "IEA energy statistics database needs to be purchased from the IEA". I am attempting to figure out how expensive it is, however I'm not sure which database this refers to. I have found this one: https://webstore.iea.org/world-energy-statistics-2018, however it says that "this product is no longer available". Any help would be appreciated! Thanks!

**Comment by emcduffie** [comment]
Hi Chris,

The IEA updates their World Energy Statistics product every year around September. The current version can be found here: https://webstore.iea.org/world-energy-statistics-2019 and provides emissions through 2017 with some estimates for 2018. The USB key is 800.00 euros and gives you access to the online IEA data portal for one year. In the portal you can download both the OECD and Non-OCED energy statistics that are needed as input for the CEDS system. You will need to reformat the data for CEDS but can find the data templates at /input/energy/OECD_E_Stat_template.csv and input/energy/NonOECD_E_Stat_template.csv.

Erin

**Comment by ssmithClimate** [comment]
Chris, 

We will be releasing a new version of the code that is updated to use the IEA 2019 version of the statistics.

**Comment by ctessum** [comment]
Thanks!
