### ISSUE TITLE
Agricultural waste burning on fields (AWB) is included for some European countries

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/CEDS#30]
This should not be included in CEDS and can result in some double-counting. This will be fixed in the next release.

**Comment by ssmithClimate** [comment]
Resolved as of [Feb 05 2021](https://github.com/JGCRI/CEDS/pull/32) release.

**Comment by mich0520elle** [comment]
I can't find AWB sector in 2021-04-21 version. Where can I find AWB emissions by country? Thank you!

**Comment by ssmithClimate** [comment]
Agricultural waste burning on fields (AWB) is not included in CEDS. The data for CMIP6 was based on GFED. See "Historic global biomass burning emissions for CMIP6 (BB4CMIP) based on merging satellite observations with proxies and fire models (1750–2015) (van Marle etal 2017)" for description. That data is available in gridded form on ESGF. I'm not sure if there is an updated version.
