### ISSUE TITLE
Will CEDS work without access to IEA data?

### ISSUE THREAD

**Issue by oSamTo** [JGCRI/CEDS#34]
Hi, I am trying to run my first instance of CEDS, 

will i get anywhere without IEA data? i am not in a position to purchase proprietary data, will CEDS offer any results at all?

**Comment by ssmithClimate** [comment]
No, unfortunately it won't. Some of the early stage scripts will work, but most won't. We have plans for a fully open source version that uses a different energy dataset, but we won't be able to work on that in the near-term.

**Comment by oSamTo** [comment]
Many thanks for your reply, i shall look to other sources for now, particularly ACCMIP for some historical gridded data, and look forward to further iterations of CEDS in the future.

**Comment by ssmithClimate** [comment]
Note that our new gridded data out to 2019 is available. Look for a CEDS update either today or tomorrow.
