### ISSUE TITLE
no download from PNNL DataHub

### ISSUE THREAD

**Issue by oSamTo** [JGCRI/CEDS#36]
Hi - the PNNL DataHub does not appear to make data available for download (https://release.datahub.pnnl.gov/released_data/1677) , I cannot get beyond the in-progress status for "File Retrieval" (Chrome, edge, Firefox all the same - 3 spinning dots constantly, have left it for many hours). thanks

**Comment by GregoryFaluvegi** [comment]
Hello. Also, when CEDS announced May 27th 2021 that it should be working again via Globus, it still fails for me.
At: https://data.pnnl.gov/dataset/CEDS-4-21-21, if I click on the orange "Download" button, I get:
"Directory Not Found"
And if I search for:
CEDS_gridded_data_2021-04-21
I get no results. I tried Safari and Chrome. Thanks.

**Comment by ssmithClimate** [comment]
Same for me. I will report this problem.

**Comment by ssmithClimate** [comment]
I am told the issue has been identified, and they are working to bring this back on-line.

**Comment by ssmithClimate** [comment]
Looks like this is back up now, please let us know.

**Comment by oSamTo** [comment]
at the moment it is very problematic to download CEDS due to Globus and various firewall restrictions. I shall keep trying.

**Comment by ssmithClimate** [comment]
I'm going to close this for now. There were some initial problems, but as far as I know its working ok now. But feel free to re-open if there are still problems.
