### ISSUE TITLE
Users have requested CH4 data before 1970

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/CEDS#4]
Several modelers have requested CH4 emissions prior to 1970. CH4 emissions were released from 1970 forward because we have not processed historical data necessary to reliably extend CH4 emissions for key CH4 sectors (e.g., fossil fuel production, rice production, livestock statistics) before that point.

**Comment by rhoesly** [comment]
We have produced supplementary methane estimates prior to 1970 using CMIP5/RCP methane data (Lamarque et al 2010). CEDS 1970 estimates were scaled back to 1850 by aggregate sector and regions (26 sub-regions as defined by Larmarque data) every 10 years. While these estimates are not fully consistent with CEDS estimates, they provide longer time trends as requested, albeit with increased uncertainty. More information is available in the interactive discussion section of the [CEDS GMD journal article](https://www.geosci-model-dev-discuss.net/gmd-2017-43/) and in the final manuscript.
