### ISSUE TITLE
Zenodo dataset title may have wrong version label

### ISSUE THREAD

**Issue by chrisroadmap** [JGCRI/CEDS#50]
Hi CEDS team,

Excellent work updating emissions to 2022. Very long anticipated - thanks.

In the Zenodo dataset at https://zenodo.org/records/10904361 there may be a typo. The dataset title is v_2023_04_01, but the data files are labelled v_2024_04_01.

**Comment by rgieseke** [comment]
Ha, just came here to report the same!

Many thanks for all your work on this, @rhoesly @ssmithClimate et al.!

I also noted that it's a "new" DOI, so not part of https://zenodo.org/doi/10.5281/zenodo.3606752

I made the same mistake in the past and had mailed the Zenodo team. Back then it wasn't possible to fix that on their end but maybe it's possible now to let the 2024_04_01 release be changed to be a part of [10.5281/zenodo.3606752](https://zenodo.org/doi/10.5281/zenodo.3606752).

**Comment by rhoesly** [comment]
release title has been corrected to 2024_04_01
