### ISSUE TITLE
Link to update comparison figures not working

### ISSUE THREAD

**Issue by jkikstra** [JGCRI/CEDS#53]
Very minor issue. 

The documentation in the README.md still has a link to e.g.:
https://github.com/JGCRI/CEDS/blob/master/documentation/Version_comparison_figures_v_2024_07_08_vs_2016_07_16-CMIP6.pdf 

but these links don't work anymore.

Now it is, e.g.:
https://github.com/JGCRI/CEDS/blob/master/documentation/Version_comparison_figures_v_2024_04_01_vs_2016_07_16(CMIP6).pdf

**Comment by rhoesly** [comment]
missing documentation uploaded and links fixed
