### ISSUE TITLE
The new SO2 aircraft emission data (2017-08-30) contain non-zero before 1920 (corrected files now available)

### ISSUE THREAD

**Issue by Taichu-Y-Tanaka** [JGCRI/CEDS#6]
It seems the new aircraft data files (e.g., SO2-em-AIR-anthro_input4MIPs_emissions_CMIP_CEDS-2017-08-30_gn_185101-189912.nc; md5sum: c8d79ff6e213cbbfb620c6e551385003) contain non-zero values for aircraft emissions before 1920. So far as I have checked, the aircraft emissions of other species (BC, OC, etc) are zero until 1920.

**Comment by ssmithClimate** [comment]
Thank you very much for spotting that, you're correct, we missed this correction for SO2. We are correcting that and will post corrected emissions files.

**Comment by Taichu-Y-Tanaka** [comment]
Thank you for your prompt reply. I am looking forward to the corrected files.

**Comment by ssmithClimate** [comment]
The corrected files are now available on ESGF as:
input4MIPs.PNNL-JGCRI.emissions.CMIP.mon.CEDS-2017-10-05.SO2-em-AIR-anthro.gn

**Comment by ssmithClimate** [comment]
Issue has been resolved and will be closed. All parties who downloaded uncorrected data were notified.
